# Generated by Django 5.2.1 on 2025-05-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedThresholds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=100, unique=True)),
                ('min_heart_rate', models.FloatField()),
                ('max_heart_rate', models.FloatField()),
                ('min_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
            ],
            options={
                'verbose_name': 'Umbral por raza',
                'verbose_name_plural': 'Umbrales por raza',
            },
        ),
    ]
