# Generated by Django 5.2.1 on 2025-05-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indica si el correo fue confirmado mediante token', verbose_name='Correo verificado'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_token',
            field=models.CharField(blank=True, help_text='Token único generado durante el registro para verificar el correo', max_length=100, null=True, verbose_name='Token de verificación'),
        ),
    ]
